import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontFamily: "Helvetica",
    fontSize: 9,
  },
  headerContainer: {
    flexDirection: "row" as const,
    justifyContent: "center" as const,
    alignItems: "center" as const,
    marginBottom: 20,
    position: "relative" as const,
    width: "100%",
  },
  logo: {
    position: "absolute" as const,
    left: 0,
    top: 0,
    width: 60,
    height: 48,
    objectFit: "contain" as const,
  },
  headerTextBlock: {
    flex: 1,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    paddingHorizontal: 70,
  },
  title: {
    fontSize: 16,
    fontWeight: "bold" as const,
    marginBottom: 4,
    textAlign: "center" as const,
  },
  branchName: {
    fontSize: 12,
    marginBottom: 4,
    textAlign: "center" as const,
  },
  periodText: {
    fontSize: 10,
    color: "#555",
    textAlign: "center" as const,
  },
  tableRow: {
    flexDirection: "row" as const,
    borderBottomWidth: 1,
    borderBottomColor: "#BFBFBF",
    borderBottomStyle: "solid" as const,
    minHeight: 24,
    alignItems: "stretch" as const,
  },
  headerRow: {
    backgroundColor: "#F3F4F6",
    borderTopWidth: 1,
    borderTopColor: "#BFBFBF",
    borderTopStyle: "solid" as const,
  },
  bodyRow: {
    borderLeftWidth: 1,
    borderLeftColor: "#BFBFBF",
    borderLeftStyle: "solid" as const,
  },
  cellCode: {
    width: "15%",
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center" as const,
  },
  cellName: {
    width: "45%",
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center" as const,
  },
  cellAmount: {
    width: "20%",
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center" as const,
  },
  headerCell: {
    fontWeight: "bold" as const,
    fontSize: 10,
    textAlign: "center" as const,
  },
  cellText: {
    fontSize: 9,
    lineHeight: 1.2,
  },
  cellTextRight: {
    fontSize: 9,
    lineHeight: 1.2,
    textAlign: "right" as const,
  },
  totalsRow: {
    backgroundColor: "#E8F0FE",
    borderBottomWidth: 1,
    borderBottomColor: "#BFBFBF",
    borderBottomStyle: "solid" as const,
    borderLeftWidth: 1,
    borderLeftColor: "#BFBFBF",
    borderLeftStyle: "solid" as const,
  },
  totalsLabelCell: {
    width: "60%",
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center" as const,
    alignItems: "flex-end" as const,
  },
  totalsLabelText: {
    fontWeight: "bold" as const,
    fontSize: 10,
    color: "#1E3A5F",
  },
  totalsAmountCell: {
    width: "20%",
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
    paddingHorizontal: 4,
    paddingVertical: 6,
    justifyContent: "center" as const,
  },
  totalsAmountText: {
    fontWeight: "bold" as const,
    fontSize: 9,
    textAlign: "right" as const,
    color: "#1E3A5F",
  },
  emptyMessage: {
    textAlign: "center" as const,
    paddingVertical: 16,
    color: "#666666",
    fontSize: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#BFBFBF",
    borderBottomStyle: "solid" as const,
    borderLeftWidth: 1,
    borderLeftColor: "#BFBFBF",
    borderLeftStyle: "solid" as const,
    borderRightWidth: 1,
    borderRightColor: "#BFBFBF",
    borderRightStyle: "solid" as const,
  },
});
