import { StyleSheet } from "@react-pdf/renderer";

const colors = {
	primary: "#0F3D6E",
	primarySoft: "#E8F1FA",
	ink: "#1E293B",
	muted: "#64748B",
	line: "#CBD5E1",
	surface: "#F8FAFC",
	white: "#FFFFFF",
	success: "#0F766E",
	successSoft: "#ECFDF5",
};

export const paymentRequestPdfColors = colors;

export const paymentRequestPdfStyles = StyleSheet.create({
	page: {
		paddingTop: 16,
		paddingBottom: 14,
		paddingHorizontal: 22,
		fontSize: 8,
		fontFamily: "Helvetica",
		color: colors.ink,
		backgroundColor: colors.white,
	},
	header: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 8,
		paddingBottom: 6,
		borderBottomWidth: 1.5,
		borderBottomColor: colors.primary,
	},
	headerLeft: {
		width: "20%",
		alignItems: "flex-start",
	},
	headerCenter: {
		width: "58%",
		alignItems: "center",
		justifyContent: "center",
		paddingHorizontal: 6,
	},
	headerRight: {
		width: "22%",
		alignItems: "flex-end",
	},
	logo: {
		width: 42,
		height: 42,
		objectFit: "contain",
	},
	companyName: {
		fontSize: 11,
		fontFamily: "Helvetica-Bold",
		color: colors.primary,
		textAlign: "center",
		letterSpacing: 0.3,
	},
	documentTitle: {
		marginTop: 2,
		fontSize: 10,
		fontFamily: "Helvetica-Bold",
		color: colors.ink,
		textAlign: "center",
		letterSpacing: 0.4,
	},
	documentBadge: {
		marginTop: 3,
		paddingVertical: 2,
		paddingHorizontal: 6,
		borderRadius: 8,
		backgroundColor: colors.primarySoft,
	},
	documentBadgeText: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.primary,
		textAlign: "center",
	},
	requestNumberLabel: {
		fontSize: 6,
		color: colors.muted,
		textTransform: "uppercase",
		letterSpacing: 0.4,
	},
	requestNumberValue: {
		marginTop: 1,
		fontSize: 8,
		fontFamily: "Helvetica-Bold",
		color: colors.primary,
		textAlign: "right",
	},
	mainGrid: {
		flexDirection: "row",
		marginBottom: 6,
	},
	infoCard: {
		width: "66%",
		marginRight: 6,
		borderWidth: 1,
		borderColor: colors.line,
		borderRadius: 4,
		backgroundColor: colors.white,
		overflow: "hidden",
	},
	amountsCard: {
		width: "34%",
		borderWidth: 1,
		borderColor: colors.line,
		borderRadius: 4,
		backgroundColor: colors.surface,
		overflow: "hidden",
	},
	cardHeader: {
		backgroundColor: colors.primary,
		paddingVertical: 4,
		paddingHorizontal: 7,
	},
	cardHeaderText: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.white,
		letterSpacing: 0.4,
		textTransform: "uppercase",
	},
	cardBody: {
		paddingVertical: 5,
		paddingHorizontal: 7,
	},
	fieldRow: {
		flexDirection: "row",
		alignItems: "flex-end",
		marginBottom: 3,
	},
	fieldLabel: {
		width: "34%",
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.muted,
	},
	fieldValueWrap: {
		width: "66%",
		borderBottomWidth: 1,
		borderBottomColor: colors.line,
		paddingBottom: 1,
		minHeight: 9,
	},
	fieldValue: {
		fontSize: 7.5,
		color: colors.ink,
	},
	conceptBlock: {
		marginBottom: 3,
	},
	conceptBox: {
		marginTop: 2,
		borderWidth: 1,
		borderColor: colors.line,
		borderRadius: 3,
		backgroundColor: colors.surface,
		paddingVertical: 3,
		paddingHorizontal: 5,
		minHeight: 22,
		maxHeight: 36,
	},
	metaRow: {
		flexDirection: "row",
		marginBottom: 2,
	},
	metaItem: {
		flex: 1,
		marginRight: 6,
	},
	priorityRow: {
		flexDirection: "row",
		alignItems: "center",
		marginTop: 2,
	},
	priorityLabel: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.muted,
		marginRight: 6,
	},
	checkOption: {
		flexDirection: "row",
		alignItems: "center",
		marginRight: 8,
	},
	checkbox: {
		width: 8,
		height: 8,
		borderWidth: 1,
		borderColor: colors.primary,
		borderRadius: 1,
		alignItems: "center",
		justifyContent: "center",
		backgroundColor: colors.white,
		marginRight: 3,
	},
	checkboxChecked: {
		backgroundColor: colors.primary,
	},
	checkboxMark: {
		fontSize: 6,
		fontFamily: "Helvetica-Bold",
		color: colors.white,
		lineHeight: 1,
	},
	checkOptionLabel: {
		fontSize: 7,
		color: colors.ink,
	},
	amountRow: {
		flexDirection: "row",
		justifyContent: "space-between",
		alignItems: "center",
		paddingVertical: 2,
		borderBottomWidth: 1,
		borderBottomColor: "#E2E8F0",
	},
	amountRowLast: {
		borderBottomWidth: 0,
		marginTop: 2,
		paddingTop: 3,
		paddingBottom: 3,
		paddingHorizontal: 4,
		borderRadius: 3,
		backgroundColor: colors.successSoft,
	},
	amountLabel: {
		fontSize: 7,
		color: colors.muted,
	},
	amountValue: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.ink,
		textAlign: "right",
	},
	amountValueNet: {
		fontSize: 8,
		fontFamily: "Helvetica-Bold",
		color: colors.success,
		textAlign: "right",
	},
	section: {
		marginBottom: 6,
		borderWidth: 1,
		borderColor: colors.line,
		borderRadius: 4,
		overflow: "hidden",
	},
	tableHeader: {
		flexDirection: "row",
		backgroundColor: colors.primary,
	},
	th: {
		paddingVertical: 3,
		paddingHorizontal: 4,
		fontSize: 6,
		fontFamily: "Helvetica-Bold",
		color: colors.white,
		textTransform: "uppercase",
		letterSpacing: 0.2,
	},
	colCheck: { width: "8%" },
	colDesc: { width: "67%" },
	colComments: { width: "25%" },
	sectionTitleRow: {
		backgroundColor: colors.primarySoft,
		paddingVertical: 2,
		paddingHorizontal: 5,
		borderBottomWidth: 1,
		borderBottomColor: colors.line,
	},
	sectionTitleText: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.primary,
		letterSpacing: 0.3,
	},
	tableRow: {
		flexDirection: "row",
		borderBottomWidth: 1,
		borderBottomColor: "#E2E8F0",
		minHeight: 13,
		alignItems: "center",
	},
	tableRowAlt: {
		backgroundColor: colors.surface,
	},
	td: {
		paddingVertical: 2,
		paddingHorizontal: 4,
		fontSize: 6.5,
		color: colors.ink,
	},
	tdCenter: {
		alignItems: "center",
		justifyContent: "center",
	},
	signatures: {
		flexDirection: "row",
		marginTop: 2,
	},
	signatureCard: {
		flex: 1,
		marginRight: 6,
		borderWidth: 1,
		borderColor: colors.line,
		borderRadius: 4,
		paddingVertical: 5,
		paddingHorizontal: 6,
		minHeight: 52,
		backgroundColor: colors.white,
	},
	signatureCardLast: {
		marginRight: 0,
	},
	signatureTitle: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.primary,
		textTransform: "uppercase",
		letterSpacing: 0.3,
		marginBottom: 16,
	},
	signatureLine: {
		borderTopWidth: 1,
		borderTopColor: colors.line,
		paddingTop: 2,
	},
	signatureName: {
		fontSize: 7,
		fontFamily: "Helvetica-Bold",
		color: colors.ink,
		textAlign: "center",
	},
	signatureHint: {
		marginTop: 1,
		fontSize: 6,
		color: colors.muted,
		textAlign: "center",
	},
	footerNote: {
		marginTop: 5,
		fontSize: 6,
		color: colors.muted,
		textAlign: "center",
	},
});
