export type PayrollActionValue =
  | "report"
  | "payment_receipts"
  | "payment_requests"
  | "accumulated_history"
  | "vacation_control_report"
  | "vacation_control_area_report"
  | "vacation_accrual_area_report"
  | "income_report"
  | "deduction_report"
  | "consolidated_area_report"
  | "employee_receivables_report"
  | "monthly_ir_report"
  | "monthly_inss_report"
  | "quincenal_ir_report"
  | "quincenal_inss_report"
  | "vacation_permissions_summary_report";
