import { StyleSheet } from "@react-pdf/renderer";
export const styles = StyleSheet.create({
  page: {
    paddingTop: 108,
    paddingHorizontal: 24,
    paddingBottom: 30,
    fontSize: 9,
    fontFamily: "Helvetica",
    color: "#111827",
  },
  title: {
    fontSize: 15,
    textAlign: "center",
    fontWeight: 700,
    marginBottom: 2,
  },
  generatedAt: {
    textAlign: "center",
    marginBottom: 2,
  },
  company: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    marginBottom: 8,
  },
  headerFixed: {
    position: "absolute",
    top: 24,
    left: 24,
    right: 24,
  },
  logo: {
    position: "absolute",
    top: -12,
    left: 0,
    width: 60,
    height: 60,
    objectFit: "contain",
  },
  tableHeader: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#111827",
    paddingVertical: 2,
    marginBottom: 0,
  },
  contentWrap: {
    marginTop: 0,
  },
  row: {
    flexDirection: "row",
    paddingVertical: 1.5,
  },
  areaTitle: {
    width: "100%",
    fontSize: 11,
    fontWeight: 700,
    marginTop: 6,
    marginBottom: 4,
    backgroundColor: "#cddceb",
  },
  subtotalRow: {
    flexDirection: "row",
    borderTopWidth: 0.5,
    borderColor: "#9ca3af",
    paddingVertical: 1,
    marginTop: 0,
  },
  globalTotalRow: {
    flexDirection: "row",
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#111827",
    paddingVertical: 2,
    marginTop: 4,
  },
  colCode: { width: "13%", paddingRight: 4 },
  colName: { width: "32%", paddingRight: 6 },
  colEntryDate: { width: "16%", paddingRight: 4 },
  colAccumulated: { width: "13%", textAlign: "right", paddingRight: 2 },
  colEnjoyed: { width: "12%", textAlign: "right", paddingRight: 2 },
  colBalance: { width: "14%", textAlign: "right" },
  colLabelMerged: { width: "45%", paddingRight: 6 },
  bold: { fontWeight: 700 },
  signatureWrap: {
    position: "absolute",
    left: 24,
    right: 24,
    bottom: 18,
    textAlign: "center",
  },
});
