import { StyleSheet } from "@react-pdf/renderer";
export const styles = StyleSheet.create({
  page: {
    padding: 24,
    paddingBottom: 30,
    fontSize: 9,
  },

  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    width: "100%",
  },
  logo: {
    width: 90,
    height: 36,
    objectFit: "contain",
    marginRight: 10,
  },
  headerTextBlock: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 2,
    textAlign: "center",
  },
  branchName: {
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 2,
  },
  periodText: {
    fontSize: 8,
    color: "#555",
    textAlign: "center",
  },

  tableHeaderRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: "#f3f4f6",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    minHeight: 22,
  },

  tableRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderLeftWidth: 1,
  },

  colCodEmp: {
    width: 42,
    flexShrink: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  colNombre: {
    flexGrow: 3,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 80,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  // colValor: {
  //   width: 48,
  //   flexShrink: 0,
  //   borderStyle: "solid",
  //   borderRightWidth: 1,
  //   borderBottomWidth: 1,
  //   borderColor: "#bfbfbf",
  // },
  // colUnidad: {
  //   width: 36,
  //   flexShrink: 0,
  //   borderStyle: "solid",
  //   borderRightWidth: 1,
  //   borderBottomWidth: 1,
  //   borderColor: "#bfbfbf",
  // },
  colTotal: {
    width: 78,
    flexShrink: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  colPeriodo: {
    width: 46,
    flexShrink: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
  },
  colArea: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 60,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
  },

  cellHeader: {
    margin: 0,
    paddingVertical: 4,
    paddingHorizontal: 3,
    width: "100%",
    fontSize: 7,
    fontWeight: "bold",
    lineHeight: 1.2,
  },
  cellHeaderRight: {
    margin: 0,
    paddingVertical: 4,
    paddingHorizontal: 3,
    width: "100%",
    fontSize: 7,
    fontWeight: "bold",
    textAlign: "right",
    lineHeight: 1.2,
  },
  cell: {
    paddingVertical: 2,
    paddingHorizontal: 3,
    fontSize: 7,
    lineHeight: 1.2,
  },
  cellRight: {
    paddingVertical: 2,
    paddingHorizontal: 3,
    fontSize: 7,
    lineHeight: 1.2,
    textAlign: "right",
  },
  cellCenter: {
    paddingVertical: 2,
    paddingHorizontal: 3,
    fontSize: 7,
    lineHeight: 1.2,
    textAlign: "center",
  },

  conceptHeaderRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#1e3a5f",
    paddingVertical: 5,
    paddingHorizontal: 8,
    marginTop: 6,
  },
  conceptHeaderText: {
    color: "#ffffff",
    fontSize: 8,
    fontWeight: "bold",
  },

  areaHeaderRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#b8d4f0",
    paddingVertical: 3,
    paddingHorizontal: 6,
    marginTop: 2,
  },
  areaHeaderText: {
    color: "#1e3a5f",
    fontSize: 7,
    fontWeight: "bold",
    textTransform: "uppercase",
  },

  conceptTotalRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderLeftWidth: 1,
    backgroundColor: "#e8f0fe",
    marginTop: 1,
  },
  conceptTotalCell: {
    paddingVertical: 2,
    paddingHorizontal: 3,
    fontSize: 7,
    fontWeight: "bold",
    color: "#1e3a5f",
    lineHeight: 1.2,
  },
  conceptTotalCellRight: {
    paddingVertical: 2,
    paddingHorizontal: 3,
    fontSize: 7,
    fontWeight: "bold",
    color: "#1e3a5f",
    lineHeight: 1.2,
    textAlign: "right",
  },

  globalTotalRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderLeftWidth: 1,
    backgroundColor: "#b8d4f0",
    marginTop: 8,
  },
  globalTotalCell: {
    paddingVertical: 3,
    paddingHorizontal: 3,
    fontSize: 7,
    fontWeight: "bold",
    color: "#1e3a5f",
    lineHeight: 1.2,
  },
  globalTotalCellRight: {
    paddingVertical: 3,
    paddingHorizontal: 3,
    fontSize: 7,
    fontWeight: "bold",
    color: "#1e3a5f",
    lineHeight: 1.2,
    textAlign: "right",
  },
});
