import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 24,
    paddingHorizontal: 24,
    fontSize: 9,
    fontFamily: "Helvetica",
  },
  headerContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  headerInner: {
    flexDirection: "row",
    alignItems: "center",
  },
  logo: {
    width: 90,
    height: 36,
    objectFit: "contain",
    marginRight: 10,
  },
  headerTextBlock: {
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 6,
  },
  branchName: {
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 2,
  },
  periodText: {
    fontSize: 8,
    color: "#555",
    textAlign: "center",
  },
  tableRow: {
    flexDirection: "row",
    width: "100%",
  },
  headerRow: {
    backgroundColor: "#e5e7eb",
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderTopWidth: 1,
    borderLeftWidth: 1,
  },
  bodyRow: {
    borderStyle: "solid",
    borderColor: "#d1d5db",
    borderLeftWidth: 1,
  },
  cellCode: {
    flexGrow: 1.2,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#d1d5db",
    padding: 4,
    justifyContent: "center",
  },
  cellName: {
    flexGrow: 2.5,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#d1d5db",
    padding: 4,
    justifyContent: "center",
  },
  cellAmount: {
    flexGrow: 1.2,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#d1d5db",
    padding: 4,
    justifyContent: "center",
  },
  cellObservation: {
    flexGrow: 2,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#d1d5db",
    padding: 4,
    justifyContent: "center",
  },
  cellText: {
    width: "100%",
    fontSize: 8,
    lineHeight: 1.2,
  },
  cellTextRight: {
    width: "100%",
    fontSize: 8,
    lineHeight: 1.2,
    textAlign: "right",
  },
  headerCell: {
    fontWeight: "bold",
    fontSize: 8,
    textAlign: "center",
  },
  emptyMessage: {
    textAlign: "center",
    paddingVertical: 16,
    color: "#666666",
    fontSize: 9,
    borderWidth: 1,
    borderColor: "#d1d5db",
  },
});
