import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    padding: 24,
    paddingBottom: 30,
    fontSize: 9,
  },

  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    width: "100%",
  },
  logo: {
    width: 90,
    height: 36,
    objectFit: "contain",
    marginRight: 10,
  },
  headerTextBlock: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  title: {
    fontSize: 13,
    fontWeight: "bold",
    marginBottom: 2,
    textAlign: "center",
  },
  branchName: {
    fontSize: 11,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 2,
  },
  periodText: {
    fontSize: 8,
    color: "#555",
    textAlign: "center",
  },

  tableHeaderRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: "#f3f4f6",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    minHeight: 22,
  },

  tableRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderLeftWidth: 1,
  },

  colSmall: {
    flexGrow: 0.8,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 3,
  },
  colCode: {
    flexGrow: 1.5,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 3,
  },
  colMedium: {
    flexGrow: 1.2,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 3,
  },
  colLarge: {
    flexGrow: 2,
    flexShrink: 1,
    flexBasis: 0,
    minWidth: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 3,
  },

  cellHeader: {
    margin: 0,
    paddingVertical: 4,
    paddingHorizontal: 2,
    width: "100%",
    fontSize: 6,
    fontWeight: "bold",
    lineHeight: 1.2,
    textAlign: "center",
  },
  cellCenter: {
    width: "100%",
    fontSize: 6,
    lineHeight: 1.2,
    textAlign: "center",
  },
  cellLeft: {
    width: "100%",
    fontSize: 6,
    lineHeight: 1.2,
    textAlign: "left",
  },
  cellRight: {
    width: "100%",
    fontSize: 6,
    lineHeight: 1.2,
    textAlign: "right",
  },

  globalTotalRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderLeftWidth: 1,
    backgroundColor: "#b8d4f0",
    marginTop: 8,
  },
  globalTotalCellRight: {
    width: "100%",
    fontSize: 6,
    fontWeight: "bold",
    color: "#1e3a5f",
    lineHeight: 1.2,
    textAlign: "right",
  },
  
  signatureContainer: {
    marginTop: 40,
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
  },
  signatureBlock: {
    alignItems: "center",
    width: 200,
  },
  signatureLine: {
    width: 180,
    borderTopWidth: 1,
    borderColor: "#000",
    marginBottom: 4,
  },
  signatureText: {
    fontSize: 8,
    textAlign: "center",
  },
  signatureRole: {
    fontSize: 8,
    textAlign: "center",
    color: "#555",
  },
  signatureImage: {
    width: 100,
    height: 40,
    objectFit: "contain",
    marginBottom: 5,
  },
  
  headerGroupRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "stretch",
    backgroundColor: "#e5e7eb",
    borderStyle: "solid",
    borderColor: "#bfbfbf",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    minHeight: 14,
  },
  colGroupDolares: {
    flexGrow: 3.6,
    flexShrink: 1,
    flexBasis: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 2,
  },
  colGroupCordobas: {
    flexGrow: 3.6,
    flexShrink: 1,
    flexBasis: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
    justifyContent: "center",
    alignSelf: "stretch",
    padding: 2,
  },
  colEmptyGroup: {
    flexGrow: 11.1,
    flexShrink: 1,
    flexBasis: 0,
    borderStyle: "solid",
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderColor: "#bfbfbf",
  }
});
